import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./AuthProvider";
import { Toaster } from "react-hot-toast";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/Navigation/SideBar/Sidebar";

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <AuthProvider>
      <html lang="en">
        <body className={` ${poppins.variable} antialiased`}>
           <SidebarProvider  >
      <AppSidebar />
       <SidebarTrigger />
          {children}
           </SidebarProvider>
      <Toaster
  position="top-center"
  reverseOrder={false}
/>
        </body>
      </html>
    </AuthProvider>
  );
}
